# Generated by Django 2.1.5 on 2019-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerID', models.CharField(max_length=100, null=True)),
                ('PortID', models.CharField(max_length=100, null=True)),
                ('PortName', models.CharField(max_length=100, null=True)),
                ('PortExportDate', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['PortExportDate'],
            },
        ),
    ]
