# Generated by Django 2.2.3 on 2019-08-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerID', models.CharField(max_length=100, null=True)),
                ('Temper', models.CharField(max_length=100, null=True)),
                ('Humid', models.CharField(max_length=100, null=True)),
                ('SetTemper', models.CharField(max_length=100, null=True)),
                ('SetHumid', models.CharField(max_length=100, null=True)),
                ('Door', models.CharField(max_length=100, null=True)),
                ('UpTemper', models.CharField(max_length=100, null=True)),
                ('DoTemper', models.CharField(max_length=100, null=True)),
                ('UpHumid', models.CharField(max_length=100, null=True)),
                ('DoHumid', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
