# Generated by Django 2.2.3 on 2019-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerID', models.CharField(max_length=200, null=True)),
                ('Temper', models.CharField(max_length=200, null=True)),
                ('Humid', models.CharField(max_length=200, null=True)),
                ('Door', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
