# Generated by Django 2.2.3 on 2019-07-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20190730_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='DoHumid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='DoTemper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='SetHumid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='SetTemper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='UpHumid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='UpTemper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='ContainerID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Door',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Humid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Temper',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
