# Generated by Django 2.2.3 on 2019-08-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20190731_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='ContainerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Container'),
        ),
    ]
