# Generated by Django 2.2.3 on 2019-08-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20190819_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='ContainerID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
