# Generated by Django 2.2.3 on 2019-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190712_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='batteryInfo',
            new_name='BatteryInfo',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='vibInfo',
            new_name='SecInfo',
        ),
        migrations.AddField(
            model_name='container',
            name='VibInfo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
