# Generated by Django 2.2.3 on 2019-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190714_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='PortExportDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
