# Generated by Django 2.1.1 on 2019-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_num', models.IntegerField()),
                ('Device_name', models.CharField(max_length=10)),
                ('Device_status', models.BooleanField()),
            ],
        ),
    ]
