# Generated by Django 2.2.4 on 2019-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20190812_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='EnforceH_Do',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='device',
            name='EnforceH_UP',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='device',
            name='EnforceT_Do',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='device',
            name='EnforceT_Up',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='DoTemper',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='UpTemper',
            field=models.NullBooleanField(),
        ),
    ]
