# Generated by Django 2.2.3 on 2019-08-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerID', models.CharField(max_length=100, null=True)),
                ('SizeType', models.CharField(max_length=100, null=True)),
                ('TotalWeight', models.CharField(max_length=100, null=True)),
                ('GoodsName', models.CharField(max_length=100, null=True)),
                ('GoodsClassify', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
                ('LeavePlace', models.CharField(max_length=100, null=True)),
                ('CarryingDate', models.CharField(max_length=100, null=True)),
                ('Check', models.CharField(default='0', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-Check', '-CarryingDate'],
            },
        ),
    ]
