# Generated by Django 2.2.3 on 2019-07-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190712_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='BatteryInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='CheckDoor',
        ),
        migrations.RemoveField(
            model_name='container',
            name='CheckInOut',
        ),
        migrations.RemoveField(
            model_name='container',
            name='CheckInOutName',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ContainerInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ContainerloadInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='LaidupCode',
        ),
        migrations.RemoveField(
            model_name='container',
            name='LaidupPlace',
        ),
        migrations.RemoveField(
            model_name='container',
            name='LaidupSubCode',
        ),
        migrations.RemoveField(
            model_name='container',
            name='LocaInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='PortEntryCount',
        ),
        migrations.RemoveField(
            model_name='container',
            name='PortEntryDate',
        ),
        migrations.RemoveField(
            model_name='container',
            name='PortEntryYear',
        ),
        migrations.RemoveField(
            model_name='container',
            name='SecInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ShipEngName',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ShipKoName',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ShipTypeCode',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ShipTypeName',
        ),
        migrations.RemoveField(
            model_name='container',
            name='TemInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='VibInfo',
        ),
        migrations.RemoveField(
            model_name='container',
            name='WetInfo',
        ),
    ]
