# Generated by Django 2.1.5 on 2019-07-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_container_portexportdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['PortExportDate']},
        ),
    ]
