# Generated by Django 2.2.3 on 2019-07-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190718_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-PortExportDate']},
        ),
    ]
