# Generated by Django 2.2.3 on 2019-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190731_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='PortCheck',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
