# Generated by Django 2.2.3 on 2019-07-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_container_portcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-PortCheck', '-PortExportDate']},
        ),
    ]
