# Generated by Django 2.2.3 on 2019-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190731_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-Msn']},
        ),
        migrations.RenameField(
            model_name='container',
            old_name='PortExportDate',
            new_name='GoodsClassfiy',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='PortID',
            new_name='GoodsName',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='PortName',
            new_name='LeaveClassfiy',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='PortCheck',
            new_name='MBLNum',
        ),
        migrations.AddField(
            model_name='container',
            name='LeavePlace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='LoadID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='Msn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='Pol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='Section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='SizeType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='TotalWeight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
