# Generated by Django 2.2.3 on 2019-08-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190812_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='GoodsClassfiy',
            new_name='GoodsClassify',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='LeaveClassfiy',
            new_name='LeaveClassify',
        ),
    ]
