# Generated by Django 2.2.3 on 2019-08-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190812_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(max_length=100, null=True)),
                ('ced', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
