# Generated by Django 2.2.3 on 2019-08-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
