# Generated by Django 2.2.3 on 2019-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='CarryingDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
